/** @type {Record<string, string>} */
export const CURRENCY_CODE_TO_ICON_NAME_MAP = {
  USD: 'usa',
  EUR: 'european-union',
  RUB: 'russia',
  AUD: 'australia',
  GBP: 'united-kingdom',
  DKK: 'denmark',
  AED: 'uae',
  CAD: 'canada',
  CNY: 'china',
  KWD: 'kuwait',
  KGS: 'kyrgyzstan',
  LVL: 'latvia',
  MDL: 'moldova',
  NOK: 'norway',
  SAR: 'saudi-arabia',
  XDR: 'XDR',
  SGD: 'singapore',
  UZS: 'uzbekistan',
  UAH: 'ukraine',
  SEK: 'sweden',
  CHF: 'switzerland',
  EEK: 'latvia',
  KRW: 'south-korea',
  JPY: 'japan',
  BYN: 'belarus',
  PLN: 'poland',
  ZAR: 'south-africa',
  TRY: 'turkey',
  HUF: 'hungary',
  CZK: 'czech-republic',
  TJS: 'tajikistan',
  HKD: 'hong-kong',
  BRL: 'brazil',
  MYR: 'malaysia',
  AZN: 'azerbaijan',
  INR: 'india',
  THB: 'thailand',
  AMD: 'armenia',
  GEL: 'georgia',
  IRR: 'iran',
  MXN: 'mexico',
  KZT: 'kazakhstan',
}

/** @type {Record<string, string>} */
export const CURRENCY_CODE_TO_NAME_MAP = {
  USD: 'US Dollar',
  EUR: 'Euro',
  GBP: 'British Pound',
  AUD: 'Australian Dollar',
  NZD: 'New Zealand Dollar',
  JPY: 'Japanese Yen',
  CNY: 'Chinese Yuan',
  CHF: 'Swiss Franc',
  CAD: 'Canadian Dollar',
  MXN: 'Mexican Peso',
  INR: 'Indian Rupee',
  BRL: 'Brazilian Real',
  RUB: 'Russian Ruble',
  BTC: 'Bitcoin',
  ETH: 'Ethereum',
  AFN: 'Afghan Afghani',
  ALL: 'Albanian Lek',
  DZD: 'Algerian Dinar',
  AOA: 'Angolan Kwanza',
  ARS: 'Argentine Peso',
  AMD: 'Armenian Dram',
  AZN: 'Azerbaijani Manat',
  BSD: 'Bahamian Dollar',
  BHD: 'Bahraini Dinar',
  BDT: 'Bangladeshi Taka',
  BYR: 'Belarusian Ruble',
  BTN: 'Bhutanese Ngultrum',
  BOB: 'Bolivian Boliviano',
  BIH: 'Bosnian Mark',
  BWP: 'Botswanan Pula',
  BND: 'Brunei Dollar',
  BGN: 'Bulgarian Lev',
  BIF: 'Burundian Franc',
  KHR: 'Cambodian Riel',
  XAF: 'Central African CFA Franc',
  CVE: 'Cape Verdean Escudo',
  KYD: 'Cayman Islands Dollar',
  CLP: 'Chilean Peso',
  COP: 'Colombian Peso',
  KMF: 'Comorian Franc',
  CDF: 'Congolese Franc',
  CRC: 'Costa Rican Colón',
  HRV: 'Croatian Kuna',
  CUC: 'Cuban Convertible Peso',
  CZK: 'Czech Republic Koruna',
  DKK: 'Danish Krone',
  DJF: 'Djiboutian Franc',
  DOP: 'Dominican Peso',
  EGP: 'Egyptian Pound',
  SVC: 'Salvadoran Colón',
  ERN: 'Eritrean Nakfa',
  ETB: 'Ethiopian Birr',
  FJD: 'Fijian Dollar',
  GMD: 'Gambian Dalasi',
  GEL: 'Georgian Lari',
  GHS: 'Ghanaian Cedi',
  GTQ: 'Guatemalan Quetzal',
  GNF: 'Guinean Franc',
  GYD: 'Guyanaese Dollar',
  HTG: 'Haitian Gourde',
  HNL: 'Honduran Lempira',
  HKD: 'Hong Kong Dollar',
  HUF: 'Hungarian Forint',
  ISK: 'Icelandic Króna',
  IDR: 'Indonesian Rupiah',
  IRR: 'Iranian Rial',
  IQD: 'Iraqi Dinar',
  ILS: 'Israeli New Sheqel',
  XOF: 'CFA Franc',
  JMD: 'Jamaican Dollar',
  JOD: 'Jordanian Dinar',
  KZT: 'Kazakhstani Tenge',
  KES: 'Kenyan Shilling',
  KWD: 'Kuwaiti dinar',
  KGS: 'Kyrgystani Som',
  LAK: 'Laotian Kip',
  LBP: 'Lebanese Pound',
  LSL: 'Lesotho Loti',
  LRD: 'Liberian Dollar',
  LYD: 'Libyan Dinar',
  MOP: 'Macanese Pataca',
  MKD: 'Macedonian Denar',
  MGA: 'Malagasy Ariary',
  MWK: 'Malawian Kwacha',
  MYR: 'Malaysian Ringgit',
  MVR: 'Maldivian Rufiyaa',
  MRO: 'Mauritanian Ouguiya',
  MUR: 'Mauritian Rupee',
  MDL: 'Moldovan Leu',
  MNT: 'Mongolian Tugrik',
  MAD: 'Moroccan Dirham',
  MZN: 'Mozambican Metical',
  MMK: 'Myanmar Kyat',
  NAD: 'Namibian Dollar',
  NPR: 'Nepalese Rupee',
  XPF: 'CFP Franc',
  NIO: 'Nicaraguan Córdoba',
  NGN: 'Nigerian Naira',
  KPW: 'North Korea Currency',
  NOK: 'Norwegian Krone',
  OMR: 'Omani Rial',
  PKR: 'Pakistani Rupee',
  PAB: 'Panamanian Balboa',
  PGK: 'Papua New Guinean Kina',
  PYG: 'Paraguayan Guarani',
  PEN: 'Peruvian Nuevo Sol',
  PHP: 'Philippine Piso',
  PLN: 'Polish Zloty',
  QAR: 'Qatari Rial',
  RON: 'Romanian Leu',
  RWF: 'Rwandan Franc',
  STD: 'São Tomé & Príncipe Dobra',
  SAR: 'Saudi Riyal',
  RSD: 'Serbian Dinar',
  SCR: 'Seychellois Rupee',
  SLL: 'Sierra Leonean Leone',
  SGD: 'Singapore Dollar',
  SOS: 'Somali Shilling',
  ZAR: 'South African Rand',
  KRW: 'South Korean Won',
  SSP: 'South Sudanese Pound',
  LKR: 'Sri Lankan Rupee',
  SDG: 'Sudanese Pound',
  SRD: 'Surinamese Dollar',
  SZL: 'Swazi Lilangeni',
  SEK: 'Swedish Krona',
  SYP: 'Syrian Pound',
  TWD: 'New Taiwan Dollar',
  TJS: 'Tajikistani Somoni',
  TZS: 'Tanzanian Shilling',
  THB: 'Thai Baht',
  TTD: 'Trinidad & Tobago Dollar',
  TND: 'Tunisian Dinar',
  TRY: 'Turkish Lira',
  TMT: 'Turkmenistani Manat',
  UGX: 'Ugandan Shilling',
  UAH: 'Ukrainian Hryvnia',
  AED: 'UAE Dirham',
  UYU: 'Uruguayan Peso',
  UZS: 'Uzbekistan Som',
  VES: 'Venezuelan Bolivar',
  VND: 'Vietnamese Dong',
  YER: 'Yemeni Rial',
  ZMW: 'Zambia Kwacha',
  RTGS: 'Zimbabwean RTGS Dollar',
}

/** @type {Record<string, number>} */
export const CURRENCY_ORDER_MAP = {
  USD: 100,
  KZT: 10,
  EUR: 1,
  RUB: 1,
  KGS: 1,
  GBP: 1,
  CNY: 1,
}
